name: Deploy Astro S3

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # ソースを取得
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '22'

      - run: npm ci

      - run: npm run build  

      # AWS OICD 認証
      - uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-region: 'ap-northeast-1' 
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}

      # S3 に同期 (差分アップ & 古いファイルは削除)
      - name: S3 に同期 (差分アップ & 古いファイルは削除)
        env:
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
        run: |
          aws s3 sync dist/ s3://$S3_BUCKET --delete

      # CloudFront キャッシュ無効化
      - name: CloudFront キャッシュ無効化
        env:
          CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
        run: |
          aws cloudfront create-invalidation \
            --distribution-id $CLOUDFRONT_DISTRIBUTION_ID \
            --paths "/*"